package com.gstudios.thandhi

import com.google.common.collect.ImmutableList

object LanguageConstants {

    val AllLanguage: ImmutableList<String> = ImmutableList.of(
        "Afrikaans",
        "Arabic",
        "Belarusian",
        "Bulgarian",
        "Bengali",
        "Catalan",
        "Czech",
        "Welsh",
        "Danish",
        "German",
        "Greek",
        "English",
        "Esperanto",
        "Spanish",
        "Estonian",
        "Farsi",
        "Finnish",
        "French",
        "Irish",
        "Galician",
        "Gujarati",
        "Hebrew",
        "Hindi",
        "Croatian",
        "Haitian Creole",
        "Hungarian",
        "Indonesian",
        "Icelandic",
        "Italian",
        "Japanese",
        "Georgian",
        "Kannada",
        "Korean",
        "Lithuanian",
        "Latvian",
        "FYRO Macedonian",
        "Marathi",
        "Malay",
        "Maltese",
        "Dutch",
        "Norwegian",
        "Polish",
        "Portuguese",
        "Romanian",
        "Russian",
        "Slovak",
        "Slovenian",
        "Albanian",
        "Swedish",
        "Swahili",
        "Tamil",
        "Telugu",
        "Thai",
        "Tagalog",
        "Turkish",
        "Ukrainian",
        "Urdu",
        "Vietnamese",
        "Chinese"
    )
}